### ISSUE TITLE
V-79065 - Get-DbaUserPermission

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbadisa#11]
Already created - just export it. This is a wrap of permissions.sql

**Comment by tboggiano** [comment]
just checking, would assume export to a csv

**Comment by potatoqualitee** [comment]
yep! there are times when i do Get and just use examples to show Export but making this anexport command should work

**Comment by potatoqualitee** [comment]
did this one! 🎉  Get-DbsDbPermission and Get-DbsDbPermission
