### ISSUE TITLE
V-79073 - Set-DbaDbAuditMaintainer

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbadisa#15]
Create a database role specifically for audit maintainers, and give it permission to maintain audits, without granting it unnecessary permissions (The role name used here is an example; other names may be used.):

```
foreach ($db in $dbs) {
    $db.Query("CREATE ROLE DATABASE_AUDIT_MAINTAINERS")
    $db.Query("GRANT ALTER ANY DATABASE AUDIT TO DATABASE_AUDIT_MAINTAINERS")
}
```

Then add the following code. Too hungry to convert to PowerShell right now 😅 

> Use REVOKE and/or DENY and/or ALTER ROLE ... DROP MEMBER ... statements to remove the ALTER ANY DATABASE AUDIT permission from all users. 

> Use REVOKE and/or DENY and/or ALTER SERVER ROLE ... DROP MEMBER ... statements to remove CONTROL DATABASE permission from logins that do not need it.

```
foreach ($dbuser in $dbusers) {
    $db.Query("REVOKE WHATEVER")
    $db.Query("remove CONTROL DATABASE")
}
```

Then, for each **authorized** database user, run the statement:

```
foreach ($dbuser in $dbusers) {
    $db.Query("ALTER ROLE DATABASE_AUDIT_MAINTAINERS ADD MEMBER")
}
```

**Comment by tboggiano** [comment]
Question what should we do in the event that a user they are attempting to add doesn't exist in the database?

**Comment by potatoqualitee** [comment]
Mmm probably a warning then continue on?

**Comment by potatoqualitee** [comment]
hey @tboggiano - how's this going?

**Comment by potatoqualitee** [comment]
oh snap, got a PR, thank you!

**Comment by potatoqualitee** [comment]
to answer your question, btw, i ended up adding the user.
