### ISSUE TITLE
Start-DbsStig | V-79083

### ISSUE THREAD

**Issue by FDBTech** [sqlcollaborative/dbadisa#95]
Error: 
"Set-DbaDbRecoveryModel : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input."

PowerShell version: 5.1 for Windows

dbadisa version: 0.1.2

Description: When running Start-DbsStig with all available parameters populated, I get the above error the equivalent amount of times as there are databases in my specified instance on V-79083 before the command finishes. Taking a stab in the dark here, after reviewing the source code for Start-DbsStig, at first glance, it appears that Set-DbaDbRecoveryModel is called from a switch statement in the default case. The code block for the default case is calling the Invoke-Expression command which appears to execute the Set-DbaDbRecoveryModel command with no parameters. After the error, there is a confirmation that V-79083 was successful.

**Comment by potatoqualitee** [comment]
Thank you, this has been fixed in 1.0.4
